/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.koushikdutta.superuser;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int AlwaysButton=0x7f060007;
        public static final int EmptyWhitelistText=0x7f060001;
        public static final int LinearLayout01=0x7f060000;
        public static final int LinearLayout02=0x7f060008;
        public static final int NoButton=0x7f060006;
        public static final int ScrollView01=0x7f060002;
        public static final int WhitelistItemText=0x7f060009;
        public static final int WhitelistPackageText=0x7f06000a;
        public static final int YesButton=0x7f060005;
        public static final int requestorprocesses=0x7f060004;
        public static final int requestoruid=0x7f060003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int superuserrequest=0x7f030001;
        public static final int whitelistitem=0x7f030002;
    }
    public static final class raw {
        public static final int su=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int superuser_permissions_description=0x7f050001;
        public static final int superuser_permissions_name=0x7f050002;
    }
}
